name: CI

on:
  push:
    branches:
      - dev

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run tests
        run: ./gradlew test

      - name: Build
        run: ./gradlew build

     - name: Merge main into dev
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git fetch origin main
          git merge origin/main --no-edit

      - name: Push to main
        if: success()
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git push origin HEAD:main
